---
AWSTemplateFormatVersion: 2010-09-09

Description: EKSWSV1

Parameters:

  commonstacknameparameter:
    Type: String
    Default: iam-poc

  BranchName:
    Description: CodeCommit branch name
    Type: String
    Default: master

  RepositoryName:
    Description: CodeComit repository name
    Type: String
    Default: poc

  CodeBuildDockerImage:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:5.0
    Description: Default AWS CodeBuild image for Amazon Linux 2
    MinLength: 3
    MaxLength: 100
    ConstraintDescription: You must enter a CodeBuild Docker image

  KubectlRoleName:
    Type: String
    Default: CodePipeline-role 
    Description: IAM role used by kubectl to interact with EKS cluster
    MinLength: 3
    MaxLength: 100
    ConstraintDescription: You must enter a kubectl IAM role
  
  EcrDockerRepository:
    Type: String
    Description: The name of the ECR Repository created
    Default: demo
    MinLength: 1
    MaxLength: 100
    ConstraintDescription: You must enter the ECR Repository name
  
  CodePipelineArtifactBucket:
    Type: String
    Description: The name of the S3 Bucket created
    Default: ssm1236788
    MinLength: 1
    MaxLength: 100
    ConstraintDescription: You must enter the S3 Bucket created
  
  CodeBucket:
    Type: String
    Description: The name of the S3 Bucket created
    Default: ssm1236788
    MinLength: 1
    MaxLength: 100
    ConstraintDescription: You must enter the S3 Bucket created

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      # - Label:
      #     default: GitHub
      #   Parameters:
      #     - GitHubUser
      #     - GitHubToken
      #     - GitSourceRepo
      #     - GitBranch
      - Label:
          default: CodeBuild
        Parameters:
          - CodeBuildDockerImage
      - Label:
          default: IAM
        Parameters:
          - KubectlRoleName
      #- Label:
      #    default: EKS
      #  Parameters:
      #    - EksClusterName
      - Label:
          default: ECR
        Parameters: 
          - EcrDockerRepository
      - Lable:
          default: s3
        Parameters:
          - CodePipelineArtifactBucket
    ParameterLabels:
      # GitHubUser:
      #   default: Username
      # GitHubToken:
      #   default: Access token
      # GitSourceRepo:
      #   default: Repository
      # GitBranch:
      #   default: Branch
      CodeBuildDockerImage:
        default: Docker image
      KubectlRoleName:
        default: kubectl IAM role
      #EksClusterName:
      #  default: EKS cluster name
      EcrDockerRepository:
        default: ECR Repository Name
      CodePipelineArtifactBucket:
        default: CodePipeline-Artifacts  s3 Bucket Name
      CodeBucket:
        default: s3 Code bucket 


Resources:

  AmazonCloudWatchEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join 
            - ''
            - - 'arn:aws:codecommit:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref RepositoryName
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref BranchName
      Targets:
        - Arn: !Join 
            - ''
            - - 'arn:aws:codepipeline:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref CodePipeline
          RoleArn: 
            'Fn::ImportValue': !Sub '${commonstacknameparameter}-CloudWatchEventRoleArn'
          Id: codepipeline-AppPipeline


  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Type: LINUX_CONTAINER
        Image: !Ref CodeBuildDockerImage
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrDockerRepository}
          - Name: REPOSITORY_NAME
            Value: !Ref RepositoryName
          - Name: REPOSITORY_BRANCH
            Value: !Ref BranchName
          - Name: ENVIRONMENT_NAME
            Value: !Ref BranchName
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: 
        'Fn::ImportValue': !Sub '${commonstacknameparameter}-CodeBuildServiceRoleArn'
      #VpcConfig:
      #    SecurityGroupIds: 
      #      - sg-0c27b861adc1200f8
      #    Subnets: 
      #      - subnet-06d809b8f90e8b4c4
      #      - subnet-081a0bf6598f58f0d
      #      - subnet-06a1beb0962efffd7
      #    VpcId: vpc-0c44b0ac36a5aa7d1
 
 
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: 
        'Fn::ImportValue': !Sub '${commonstacknameparameter}-CodePipelineServiceRoleArn'
      Name: !Sub ${AWS::StackName}-pipeline
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: !Ref BranchName
                RepositoryName: !Ref RepositoryName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
    DependsOn: 
      - CodeBuildProject